network = "testnet"

[datastore_config]
type = "GCS"

[datastore_config.params]
destination_url = "gcs://exporter-test/ledgers"

[exporter_config]
  ledgers_per_file = 1
  files_per_partition = 64000

